FROM openjdk:17-slim
WORKDIR /app

# Kopírování již sestaveného JAR souboru
COPY target/DetApp-1.0-SNAPSHOT.jar app.jar

# Expose port 8090
EXPOSE 8090

# Spuštění aplikace
ENTRYPOINT ["java", "-jar", "app.jar"]